require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
$RNFirebaseAsStaticFramework = true
# Override Firebase SDK Version


target 'MureedR' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

# add the Firebase pod for Google Analytics

# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
pod 'Firebase/Core'


  target 'MureedRTests' do
    inherit! :complete
    # Pods for testing
  end





  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  
end

target 'MureedR-tvOS' do
  # Pods for MureedR-tvOS

  target 'MureedR-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
